version: '2'

services:
  dev:
    build:
      context: .
    container_name: wordpress-sqlite
    volumes:
      - ./database:/wordpress/wp-content/database
      - ./uploads:/wordpress/wp-content/uploads
      - ./plugins:/wordpress/wp-content/plugins
      - ./themes:/wordpress/wp-content/themes
    restart: always
    entrypoint: sh -c "cd wordpress && php -S 0.0.0.0:8000"
    ports:
      - "8000:8000"
