version: '3'

services:
  dev:
    build:
      context: .
    container_name: wordpress-sqlite
    volumes:
      - .:/test
      - ./database:/wordpress/wp-content/database
      - ./uploads:/wordpress/wp-content/uploads
      - ./plugins/starter:/wordpress/wp-content/plugins/starter
      - ./themes/starter:/wordpress/wp-content/themes/starter
    restart: always
    entrypoint: sh -c "cd wordpress && php -S 0.0.0.0:8000"
    ports:
      - "8000:8000"
